[package]
name = "tikv_util"
version = "0.1.0"
edition = "2018"
publish = false

[features]
failpoints = ["fail/failpoints"]
protobuf-codec = ["kvproto/protobuf-codec"]
prost-codec = ["kvproto/prost-codec"]

[dependencies]
async-speed-limit = "0.3"
backtrace = "0.3.9"
byteorder = "1.2"
codec = { path = "../codec" }
configuration = { path = "../configuration" }
chrono = "0.4"
crc32fast = "1.2"
crossbeam = "0.7.2"
error_code = { path = "../error_code" }
derive_more = "0.99.3"
fail = "0.3"
fs2 = "0.4"
futures = "0.1"
futures03 = { package = "futures", version = "0.3" }
fxhash = "0.2.1"
grpcio = { version = "0.5", default-features = false, features = ["openssl-vendored"] }
hex = "0.4"
lazy_static = "1.3"
libc = "0.2"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
num_cpus = "1"
openssl = "0.10"
prometheus = { version = "0.8", features = ["nightly", "push"] }
quick-error = "1.2.3"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = "2.3"
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
slog-json = "2.3"
slog-term = "2.4"
sysinfo = "0.14"
tikv_alloc = { path = "../tikv_alloc" }
time = "0.1"
tipb = { git = "https://github.com/pingcap/tipb.git", default-features = false }
tokio = { version = "0.2", features = ["rt-util"] }
tokio-core = "0.1"
tokio-executor = "0.1"
tokio-timer = "0.2"
url = "2"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
minitrace = { git = "https://github.com/pingcap-incubator/minitrace-rust.git", rev = "9943d799673dde35fae97c2189f3de4c006af384", features = ["jaeger"] }
protobuf = "2.8"

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = { git = "https://github.com/tikv/procinfo-rs", rev = "5125fc1a69496b73b26b3c08b6e8afc3c665a56e" }
procfs = "0.7"

[dependencies.yatp]
git = "https://github.com/tikv/yatp.git"

[dev-dependencies]
futures-cpupool = "0.1"
panic_hook = { path = "../panic_hook" }
protobuf = "2"
regex = "1.0"
tempfile = "3.0"
toml = "0.4"
utime = "0.2"
